'use client'
import Link from "next/link"

export default function TermsOfService() {
  return (
    <div className="max-w-4xl py-12 text-center mx-auto">
      <div className="space-y-6">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">TERMINOS DE SERVICIO</h1>
          <p className="text-sm text-muted-foreground">Última Actualización: Mayo 21, 2025</p>
        </div>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold">INTRODUCCIÓN</h2>
          <p className="text-justify">
            Lea atentamente estos términos de servicio y nuestra Política de Privacidad (en conjunto, los &quot;Términos&quot;), ya que constituyen un contrato entre usted 
            y nosotros y rigen el uso y acceso a los Servicios de Skinner por parte de usted. En caso de conflicto entre estos términos de servicio y 
            nuestra Política de Privacidad, prevalecerán estos términos de servicio.
            Al acceder o utilizar los Servicios de Skinner, usted acepta estar sujeto a estos Términos. 
            Si acepta estos Términos en nombre de una empresa, organización u otra entidad legal (una &quot;Entidad&quot;), acepta estos Términos en nombre de 
            dicha Entidad y nos declara que tiene la autoridad para vincular a dicha Entidad y sus Afiliados a estos Términos. 
            En cuyo caso, los términos &quot;Usted&quot;,&quot;Su&quot; o términos similares en mayúsculas utilizados en este documento se referirán a dicha Entidad y sus Afiliados. 
            Si no tiene dicha autorización o no está de acuerdo con estos Términos, no debe aceptarlos y no podrá acceder ni utilizar los Servicios.
            Usted, como persona física, debe ser mayor de 18 años para acceder o utilizar los servicios.
            </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold">DEFINICIONES</h2>
          <p className="text-justify mb-4"> Cuando se utilizan en estos Términos con la letra inicial en mayúscula, tienen los siguientes significados:</p>
          <p className="text-justify mb-4 space-y-4"><strong>Cuenta:</strong> se refiere a cualquier cuenta creada por usted o en su nombre para acceder y utilizar cualquiera de los Servicios.</p>
          <p className="text-justify mb-4 space-y-4"><strong>Leyes aplicables:</strong> Se referirá a las leyes a las que está sujeto Skinner, en particular las Leyes de El Salvador, donde Skinner tiene su sede y cualquier otra ley que pueda ser aplicable en ese momento.</p>
          <p className="text-justify mb-4 space-y-4"><strong>Confidencial</strong> significa toda la información revelada por Usted a Nosotros o por Nosotros a Usted que está en forma 
            tangible y etiquetada como &quot;confidencial&quot; (o con una leyenda similar) o que una persona razonable entendería como confidencial dada 
            la naturaleza de la información y las circunstancias de la divulgación. Para los propósitos de estos Términos, Sus Datos se considerarán 
            Información Confidencial. Sin perjuicio de lo anterior, la Información Confidencial no incluirá ninguna información que (a) fuera públicamente 
            conocida y se pusiera a disposición del público general antes del momento de la divulgación por la parte divulgadora; (b) se vuelva públicamente 
            conocida y se ponga a disposición del público general después de la divulgación por la parte divulgadora a la parte receptora sin acción 
            u omisión de la parte receptora; (c) ya esté en posesión de la parte receptora en el momento de la divulgación por la parte divulgadora como lo 
            demuestran los archivos y registros de la parte receptora antes del momento de la divulgación; (d) sea obtenida por la parte receptora de un 
            tercero sin un incumplimiento de las obligaciones de confidencialidad de dicho tercero; (e) es desarrollada independientemente por la parte 
            receptora sin usar ni hacer referencia a la Información Confidencial de la parte reveladora, como lo demuestran los documentos y otras pruebas 
            competentes en posesión de la parte receptora; o (f) la ley exige que la parte receptora la divulgue, siempre que la parte receptora dé a la parte 
            reveladora un aviso escrito de dicho requisito de divulgación lo antes posible y coopere con la parte reveladora para limitar dicha divulgación.
            requisito antes de la divulgación para que la parte reveladora pueda buscar una orden de protección u otro alivio apropiado.</p>
           <p className="text-justify mb-4 space-y-4"><strong>Documentación:</strong> se refiere a cualquier documentación escrita o electrónica, imagen, video, texto o sonido que especifique las funcionalidades del/de los Servicio(s) proporcionado(s) o puesto(s) a disposición por Nosotros para Usted o sus Usuarios a través del/de los Servicio(s) o de otro modo.</p>
          <p className="text-justify mb-4 space-y-4"><strong>Formulario:</strong> se refiere a cualquier formulario de solicitud de servicio que haga referencia a estos Términos y que haya sido firmado o aprobado por Usted y por Nosotros en relación con su suscripción al/a los Servicio(s). Dicho formulario puede detallar, entre otros aspectos, el número de Usuarios autorizados a utilizar el/los Servicio(s) bajo su suscripción y el/los Plan(es) de Servicio aplicable(s). </p>
          <p className="text-justify mb-4 space-y-4"><strong>Datos Personales:</strong> se refiere a los datos relativos a una persona física que es o puede ser identificada, ya sea a partir de los datos o a partir de estos en conjunto con otra información.</p>
          <p className="text-justify mb-4 space-y-4"><strong>Política de Privacidad:</strong> se refiere a nuestra política de privacidad disponible en www.skinnersv.net, con sus actualizaciones periódicas.</p>
          <p className="text-justify mb-4 space-y-4"><strong>Tratamiento/Procesamiento:</strong>  se refiere a cualquier operación o conjunto de operaciones que se realice sobre Datos Personales, ya sea por medios automáticos o no, como la recopilación, el registro, la organización, el almacenamiento, la adaptación o alteración, la recuperación, la consulta, el uso, la divulgación por transmisión, la difusión o cualquier otra forma de puesta a disposición, la alineación o combinación, el bloqueo, la supresión o la destrucción.</p>
          <p className="text-justify mb-4 space-y-4"><strong>Política de seguridad:</strong> significa las políticas de seguridad para los Servicios publicadas en nuestro sitio web.</p>
          <p className="text-justify mb-4 space-y-4"><strong> Servicio(s):</strong> se refiere al servicio que proporciona Skinner, el Software y cualquier Documentación. Puede suscribirse a uno o más de los Servicios. Estos pueden estar sujetos a Planes de Servicio independientes.</p>
          <p className="text-justify mb-4 space-y-4"><strong> Plan(es) de Servicio:</strong>  se refiere al plan de precios y a las funcionalidades y servicios asociados tal como se detalla en el Sitio Web, a los que se suscribe con respecto a cualquier Usuario.</p>
          <p className="text-justify mb-4 space-y-4"><strong>Software:</strong>   se refiere al software proporcionado por Nosotros (ya sea mediante descarga o acceso a través de internet) que le permite utilizar cualquier funcionalidad relacionada con los Servicios e incluye las Aplicaciones Móviles.</p>
          <p className="text-justify mb-4 space-y-4"><strong>Plazo de Servicio:</strong>   se refiere al período durante el cual Usted ha aceptado suscribirse al/los Servicio(s) con respecto a cualquier Usuario individual.</p>
          <p className="text-justify mb-4 space-y-4"><strong>Nosotros:</strong>    se refiere a Skinner, una empresa salvadoreña. En estos Términos, &quot;Nosotros&quot; también puede denominarse &quot;Nosotros&quot; y &quot;Nuestro&quot;.</p>
          <p className="text-justify mb-4 space-y-4"><strong>Sus Datos:</strong>   se refiere a todos los datos electrónicos, textos, mensajes u otros materiales que Usted envía al/los Servicio(s) a través de su Cuenta en relación con su uso del/de los Servicio(s), incluyendo, sin limitación, los Datos Personales.</p>
        </section>


        <section className="space-y-4">
          <h2 className="text-2xl text-left font-semibold">1. SUS DERECHOS</h2>
          <p className="text-justify mb-4 space-y-4"><strong>1.1</strong> Estos Términos son aplicables durante su prueba gratuita y durante su suscripción al/los Servicio(s) a través del Plan de Servicio que usted elija.</p>
          <p className="text-justify mb-4 space-y-4"><strong>1.2 Uso de nuestro/s Servicio(s):</strong> Sujeto a su cumplimiento de los Términos y únicamente durante el Plazo de Suscripción, usted tiene el derecho limitado, no exclusivo y revocable de acceder y utilizar el/los Servicio(s) para sus fines comerciales internos. Usted será responsable del uso que terceros hagan del/de los Servicio(s) a través de su Cuenta. Puede suscribirse a uno o más Servicios. Estos pueden estar sujetos a Planes de Servicio independientes y distintos.</p>

        </section>

        <section className="space-y-4">
          <h2 className="text-2xl text-left font-semibold">2. SUS RESPONSABILIDADES</h2>
          <p className="text-justify mb-4 space-y-4"><strong>2.1 Su Cuenta:</strong> Sujeto a cualquier limitación en el número de Usuarios individuales disponibles bajo el Plan de Servicio al que se suscribió, el acceso y uso del/de los Servicio(s) está restringido al número especificado de Usuarios individuales permitidos bajo su suscripción al/a los Servicio(s). Cada Usuario se identificará mediante información de inicio de sesión única, como nombre de usuario y contraseña (&quot;Inicio de Sesión&quot;), y dicha información solo podrá ser utilizada por una persona. Usted es responsable de la confidencialidad de sus Datos y de su Información de Inicio de Sesión. Por lo tanto, no debe compartir su Información de Inicio de Sesión con terceros. En cualquier caso, a menos que nos notifique cualquier uso no autorizado o actividad sospechosa en su Cuenta, usted es responsable de todas las actividades que se realicen en su Cuenta. Skinner no será responsable de ningún daño o pérdida que pueda resultar de su falta de protección de su información de inicio de sesión, incluida su contraseña. Sin perjuicio de lo anterior, usted es el único responsable de garantizar que su uso del/de los Servicio(s) para almacenar y transmitir sus Datos cumpla con todas las leyes y normativas aplicables. Usted también mantiene toda la responsabilidad de determinar si el Servicio(s) o la información generada por éste es precisa o suficiente para sus propósitos.</p>
          <p className="text-justify mb-4 space-y-4"><strong>2.2 Uso del/de los Servicio(s):</strong> Usted se compromete a no licenciar, sublicenciar, vender, revender, alquilar, arrendar, transferir, ceder, distribuir, compartir en régimen de tiempo ni explotar comercialmente ni poner a disposición de terceros, salvo los Usuarios, el/los Servicio(s), para el cumplimiento de sus fines comerciales internos, tal como se permite expresamente en estos Términos; </p>
          <p className="text-justify mb-4 space-y-4">Utilizar el/los Servicio(s) para procesar datos en nombre de terceros, salvo sus Usuarios; modificar, adaptar o piratear el/los Servicio(s), ni intentar obtener acceso no autorizado al/a los Servicio(s) o a los sistemas o redes relacionados; insinuar falsamente cualquier patrocinio o asociación con Nosotros; utilizar el/los Servicio(s) de forma ilegal, incluyendo, entre otros, la violación de los derechos de privacidad de cualquier persona;</p>
          <p className="text-justify mb-4 space-y-4">Utilizar el/los Servicio(s) de cualquier manera que interfiera o altere la integridad o el rendimiento del/de los Servicio(s) y sus componentes;</p>
          <p className="text-justify mb-4 space-y-4">Intentar descifrar, descompilar, aplicar ingeniería inversa, desensamblar, reproducir, copiar, acceder o descubrir de cualquier otra forma el código fuente o el programa subyacente de cualquier Software que componga el/los Servicio(s);</p>
          <p className="text-justify mb-4 space-y-4">Intentar usar o usar el/los Servicio(s) en violación de estos Términos.</p>
          <p className="text-justify mb-4 space-y-4">Usted será responsable de cualquier pérdida de datos o de cualquier intento o acceso o uso real del/de los Servicio(s) a través de Su Cuenta en violación de estos Términos.</p>
          <p className="text-justify mb-4 space-y-4">Si le informamos que una actividad o propósito específico está prohibido con respecto a los Servicios, usted se asegurará de dejar inmediatamente de usar los Servicios para dicha actividad o propósito prohibido.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl text-left font-semibold">3. ACCESO A LOS SERVICIOS</h2>
          <p className="text-justify mb-4 space-y-4"><strong>3.1 :</strong> Usted es responsable de obtener y mantener las conexiones de red que lo conectan a los Servicios. Su acceso y uso de los Servicios puede requerir el uso o mantenimiento de software de navegación específico, certificaciones de seguridad y otros procedimientos compatibles con los protocolos utilizados por los Servicios.</p>
          <p className="text-justify mb-4 space-y-4"><strong>3.2 :</strong> Es posible que no pueda acceder ni utilizar los Servicios (a) durante periodos de inactividad planificados para actualizaciones y mantenimiento de los Servicios (de los cuales haremos todos los esfuerzos comercialmente razonables para notificarle con antelación a través de Nuestros Servicios) (“Periodos de Inactividad Planificados”), o (b) durante cualquier indisponibilidad causada por circunstancias fuera de Nuestro control razonable, como, entre otras, casos fortuitos, actos gubernamentales, actos terroristas o disturbios civiles, fallos técnicos fuera de Nuestro control razonable (incluida, entre otras, la imposibilidad de acceder a internet) o actos de terceros, incluidos, entre otros, ataques distribuidos de denegación de servicio.</p>
          <p className="text-justify mb-4 space-y-4"><strong>3.3 :</strong> Haremos todos los esfuerzos comercialmente razonables para programar un tiempo de inactividad planificado para los fines de semana (zona Hora Central) y otras horas de menor actividad.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl text-left font-semibold">4. CAMBIOS EN EL/LOS SERVICIO(S) Y SITIO WEB</h2>
          <p className="text-justify mb-4 space-y-4"><strong>4.1 Nuestro(s) Servicio(s):</strong> Podemos actualizar el/los Servicio(s) periódicamente y Usted puede recibir notificaciones de dichas mejoras o actualizaciones (&quot;Actualizaciones&quot;). Cualquier función nueva o modificada que se añada, amplíe o modifique el/los Servicio(s), así como cualquier otra actualización, modificación o mejora del/de los Servicio(s), también está sujeta a estos Términos y Nos reservamos el derecho de implementar Actualizaciones en cualquier momento.</p>
          <p className="text-justify mb-4 space-y-4"><strong>4.2 Servicios de terceros y conexiones de red:</strong> No nos responsabilizamos de notificarle sobre actualizaciones, correcciones o mejoras de dichos servicios ni de ninguna vulneración de datos, incluidos Sus Datos, transmitidos a través de redes informáticas o instalaciones de telecomunicaciones (incluido, entre otros, Internet) que no sean de nuestra propiedad, ni estén operadas ni controladas por Nosotros. Usted acepta que no nos responsabilizamos de la fiabilidad ni del rendimiento de ningún servicio o conexión descritos en esta subsección.</p>
          <p className="text-justify mb-4 space-y-4"><strong>4.3 Sitio web:</strong> También podemos cambiar el contenido de Nuestro sitio web en cualquier momento. Sin embargo, tenga en cuenta que el contenido de Nuestro sitio web puede estar desactualizado en cualquier momento y no tenemos la obligación de actualizarlo. Para mayor claridad, esta subsección se refiere a Nuestro sitio web, excluyendo los Servicios. Podemos interrumpir o modificar cualquier parte de Nuestro sitio web que no afecte a los Servicios, sin notificárselo. Nuestro sitio web puede contener enlaces a sitios web, contenido y recursos proporcionados por terceros (&quot;Enlaces de terceros&quot;). Estos enlaces de terceros se rigen por sus propios términos y políticas de privacidad, y usted acepta que no tenemos control sobre estos enlaces de terceros ni nos hacemos responsables de su acceso o uso de los mismos.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl text-left font-semibold">5. DERECHOS DE PROPIEDAD INTELECTUAL</h2>
          <p className="text-justify mb-4 space-y-4"><strong>5.1 Titularidad de los Derechos de Propiedad Intelectual:</strong> Salvo los derechos que se le otorgan en virtud de la Sección 1, todos los derechos, títulos e intereses sobre todas Nuestras patentes, invenciones, derechos de autor, marcas comerciales, nombres de dominio, secretos comerciales, conocimientos técnicos y cualquier otra propiedad intelectual o derecho de propiedad en o relacionado con el/los Servicio(s), incluido el Sitio Web, y cualquier parte de ellos (en conjunto, los &quot;Derechos de Propiedad Intelectual&quot;) nos pertenecerán y permanecerán exclusivamente con Nosotros. Somos los propietarios o licenciatarios de todos los Derechos de Propiedad Intelectual de Nuestro Sitio Web, así como del contenido o material publicado en el. Dichas obras están protegidas por las leyes y tratados internacionales de derechos de autor. No debe utilizar ninguna parte del contenido de Nuestro Sitio Web con fines comerciales sin obtener una licencia para ello de Nosotros. Asimismo, no reclamamos ningún derecho de propiedad intelectual sobre el contenido que usted suba o proporcione al/los Servicio(s).</p>
          <p className="text-justify mb-4 space-y-4"><strong>5.2</strong> A menos que nos notifique lo contrario por correo electrónico a info@skinnersv.net, usted acepta concedernos una licencia libre de regalías, mundial y transferible para usar su marca registrada o logotipo para identificarle como nuestro cliente en nuestro Sitios web y/o materiales de marketing.</p>
          <p className="text-justify mb-4 space-y-4"><strong>5.3</strong> Podemos obtener y agregar datos técnicos y de otro tipo sobre su uso del/de los Servicio(s) que no le identifiquen personalmente (&quot;Datos Anónimos Agregados&quot;), y podemos utilizarlos para mejorar, dar soporte y operar el/los Servicio(s). Para mayor claridad, no se le identifica como la fuente de ningún Dato Anónimo Agregado y no se recopila ningún Dato Personal como parte de dicho Dato.</p>
          <p className="text-justify mb-4 space-y-4"><strong>5.4 Concesión de licencia:</strong> Los nombres y logotipos de nuestros productos y servicios, utilizados o mostrados en el/los Servicio(s) o Sitio web, son nuestras marcas comerciales, registradas o no registradas (en conjunto, las &quot;Marcas&quot;), y solo puede utilizar dichas Marcas para identificarse como usuario del/de los Servicio(s) al/de los cual se ha suscrito.</p>
          <p className="text-justify mb-4 space-y-4"><strong>5.5 Reserva de derechos:</strong> Todos los derechos no expresamente otorgados a usted en el presente documento quedan reservados.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl text-left font-semibold">6. FACTURACIÓN, MODIFICACIONES DEL PLAN Y PAGOS</h2>
          <p className="text-justify mb-4 space-y-4"><strong>6.1 Cargos de Suscripción:</strong> Todos los cargos asociados a su Cuenta (&quot;Cargos de Suscripción&quot;) deben abonarse en su totalidad y por adelantado, de acuerdo con la Sección 6.2, al suscribirse al/a los Servicio(s). Salvo que se especifique lo contrario en un Formulario, los Cargos de Suscripción se basan en los Planes de Servicio que elija y deben abonarse en su totalidad hasta que cancele su Cuenta.</p>
          <p className="text-justify mb-4 space-y-4"><strong>6.2 Métodos de pago:</strong> Puede pagar los Cargos de Suscripción con su tarjeta de crédito/débito u otro método de pago aceptado, según se especifique en un Formulario. Por la presente, nos autoriza a nosotros, a facturar su tarjeta de crédito/débito al momento de su suscripción al/los Servicio(s) (y cualquier renovación). Para pagos con otros métodos aceptados, su pago vence dentro de los treinta (30) días posteriores a la fecha de nuestra factura, a menos que se indique lo contrario en un Formulario.</p>
          <p className="text-justify mb-4 space-y-4"><strong>6.3 Renovación:</strong> Su suscripción al/los Servicio(s) se renovará automáticamente por un Plazo de Suscripción equivalente al Plazo de Suscripción que vence en ese momento. Salvo que se disponga lo contrario en cualquier Formulario, los Cargos de Suscripción aplicables a su suscripción al/los Servicio(s) para cualquier Plazo de Suscripción posterior serán nuestros Cargos de Suscripción estándar para el Plan de Servicio al que se haya suscrito al inicio de dicho Plazo de Suscripción posterior. Usted reconoce y acepta que, a menos que cancele su Cuenta de acuerdo con la Sección 7, se cargarán automáticamente los Cargos de Suscripción aplicables a su tarjeta de crédito/débito.</p>
          <p className="text-justify mb-4 space-y-4"><strong>6.4:</strong> Podemos utilizar un proveedor de servicios externo para gestionar el procesamiento de pagos con tarjeta de crédito/débito y otros métodos de pago, siempre que dicho proveedor no esté autorizado a almacenar, conservar ni utilizar la información de su cuenta de pago, salvo para procesarla en nuestro nombre. Debe notificarnos cualquier cambio en la información de su tarjeta de crédito/débito u otra cuenta de pago, ya sea actualizando su cuenta o enviándonos un correo electrónico a info@skinnersv.net. Nuestro socio de pagos (https://www.cubopago.com/) colabora con bancos y redes de tarjetas e intenta actualizar automáticamente los datos de la tarjeta guardada cada vez que un cliente recibe una nueva (por ejemplo, al reemplazar una tarjeta caducada o una que se haya reportado como perdida o robada).</p>
          <p className="text-justify mb-4 space-y-4"><strong>6.5 Reembolsos:</strong> Salvo que se especifique lo contrario en estos Términos, en un Formulario o en un Plan de Servicio, los Cargos de Suscripción no son reembolsables. No se emitirán reembolsos por el uso parcial o la falta de uso del/de los Servicio(s).</p>
          <p className="text-justify mb-4 space-y-4"><strong>6.6 Pagos atrasados/Impago de los Cargos de Suscripción:</strong> Le notificaremos si no recibimos el pago de los Cargos de Suscripción dentro de la fecha de vencimiento de su Cuenta. Para pagos realizados con tarjetas de crédito/débito, debemos recibir los pagos adeudados en un plazo máximo de cinco (5) días a partir de la fecha de nuestra notificación, y para pagos a través de otros métodos aceptados, debemos recibir los pagos en un plazo máximo de quince (15) días a partir de la fecha de nuestra notificación. Si no recibimos el pago dentro del plazo mencionado, además de nuestro derecho a otras medidas legales disponibles, suspender su acceso y uso del/de los Servicio(s) hasta que recibamos su pago de los Cargos de Suscripción, según lo especificado en este documento; (iii) cancelar su Cuenta de acuerdo con la Sección 7.2; (iv) eliminar los datos asociados a su cuenta dentro de los sesenta (60) días siguientes al impago de la(s) factura(s) de suscripción.</p>
          <p className="text-justify mb-4 space-y-4"><strong>6.7 Impuestos Aplicables:</strong> Salvo que se indique lo contrario, los Cargos de Suscripción incluyen el impuesto al valor agregado. Le facturaremos dicho Impuestos si consideramos que tenemos la obligación legal de hacerlo y usted acepta pagarlos si se le facturan.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl text-left font-semibold">7. SUSPENSIÓN Y TERMINACIÓN</h2>
          <p className="text-justify mb-4 space-y-4"><strong>7.1 :</strong> No seremos responsables ante Usted ni ante ningún tercero por la suspensión o terminación de Su Cuenta o del acceso y uso del Servicio(s), si dicha suspensión o terminación se realiza de conformidad con estos Términos.</p>
          <p className="text-justify mb-4 space-y-4"><strong>7.2 Suspensión y Terminación por Nuestra Parte:</strong> Además de la suspensión por retraso o impago de los Cargos de Suscripción, podremos suspender su acceso y uso de su Cuenta o del/de los Servicio(s) si incumple los Términos. Le notificaremos sobre sus actividades que incumplan estos Términos y, a nuestra entera discreción, le otorgaremos un plazo de quince (15) días (&quot;Período de Subsanación&quot;) para subsanar o cesar dichas actividades. Si no subsana o cesa dichas actividades dentro de dicho Período de Subsanación, o si consideramos que su incumplimiento de estos Términos no puede subsanarse, su Cuenta será cancelada y los datos asociados a ella serán eliminados de nuestra base de datos.</p>
          <p className="text-justify mb-4 space-y-4"> Nos reservamos el derecho de cancelar la suscripción y el acceso a nuestros servicios si se realiza/utiliza lenguaje ofensivo (difamatorio, ofensivo, abusivo, indecente, amenazante o no deseado) o comentarios racistas; esto incluye cualquier forma de comunicación, contenido o interacciones que promuevan la discriminación, el odio o el daño hacia individuos o grupos en función de factores como raza, etnia, religión, género o cualquier otra característica protegida.</p>
          <p className="text-justify mb-4 space-y-4"><strong>7.3 Cancelación por su parte:</strong> Si paga su cuenta con tarjeta de crédito/débito, puede cancelarla en cualquier momento, ingresando con sus credenciales en www.skinnersv.net y eligiendo cancelar cuenta. Si realiza pagos a través de otros métodos de pago aceptados, puede cancelarla escribiendo a info@skinnersv.net.</p>
          <p className="text-justify mb-4 space-y-4"><strong>7.4 Exportación de Datos:</strong> Le recomendamos encarecidamente que exporte todos sus datos antes de cancelar su cuenta. En cualquier caso, tras la cancelación de su cuenta, ya sea por usted o por nosotros, sus datos se conservarán durante un periodo de 14 días («Periodo de Conservación de Datos») a partir de dicha cancelación, tiempo durante el cual podrá contactarnos para exportarlos. Transcurrido este periodo de conservación de datos, nos reservamos el derecho a eliminar todos sus datos durante el curso normal de la operación. Sus datos no se podrán recuperar una vez eliminados. </p>
          <p className="text-justify mb-4 space-y-4"><strong>7.5 Cargos:</strong> Si cancela su Cuenta antes de la finalización de su Período de Suscripción vigente en ese momento o si nosotros la cancelamos, además de cualquier otro importe que nos deba, deberá abonar de inmediato cualquier Cargo de Suscripción pendiente correspondiente al resto de dicho Período, a menos que le eximamos por escrito. No deberá abonar este importe si cancela su suscripción al Servicio o su Cuenta como consecuencia de un incumplimiento grave de estos Términos por nuestra parte, siempre que nos notifique dicho incumplimiento con antelación y nos conceda un plazo mínimo de treinta (30) días para subsanarlo razonablemente.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl text-left font-semibold">8. PRIVACIDAD Y SEGURIDAD DE LOS DATOS; CONFIDENCIALIDAD</h2>
          <p className="text-justify mb-4 space-y-4"><strong>8.1:</strong> Si elige o se le proporciona un código de identificación de usuario, una contraseña o cualquier otra información como parte de nuestros procedimientos de seguridad, deberá tratar dicha información como confidencial. No deberá divulgarla a terceros. Nos reservamos el derecho de desactivar cualquier código de identificación de usuario o contraseña, ya sea elegido por usted o asignado por nosotros, en cualquier momento si, a nuestro juicio razonable, ha incumplido alguna de las disposiciones de estos Términos.</p>
          <p className="text-justify mb-4 space-y-4"><strong>8.2 Obligaciones de confidencialidad:</strong> Cada uno de nosotros protegerá la Información Confidencial del otro contra el uso, acceso o divulgación no autorizados de la misma manera que cada uno de nosotros protege su propia Información Confidencial y, en cualquier caso, con un cuidado no inferior al razonable. Salvo que se permita expresamente lo contrario en virtud de estos Términos, cada uno de nosotros podrá utilizar la Información Confidencial del otro únicamente para ejercer sus respectivos derechos y cumplir con sus respectivas obligaciones en virtud de estos Términos, y divulgará dicha Información Confidencial únicamente a aquellos de nuestros respectivos empleados, que tengan necesidad de conocer dicha Información Confidencial para tales fines y que estén obligados a mantener la confidencialidad de dicha Información Confidencial y a no hacer un uso indebido de la misma.</p>          <p className="text-justify mb-4 space-y-4"><strong>7.3 Cancelación por su parte:</strong> Si paga su cuenta con tarjeta de crédito/débito, puede cancelarla en cualquier momento, ingresando con sus credenciales en www.skinnersv.net y eligiendo cancelar cuenta. Si realiza pagos a través de otros métodos de pago aceptados, puede cancelarla escribiendo a info@skinnersv.net.</p>
          <p className="text-justify mb-4 space-y-4"><strong>8.3 Seguridad de sus datos:</strong> Mantendremos medidas de seguridad administrativas, físicas y técnicas comercialmente razonables para proteger la seguridad, confidencialidad e integridad de sus datos. Estas medidas de seguridad pueden incluir el cifrado de sus datos, como se describe con más detalle en la Política de Seguridad de nuestro sitio web.</p>
          <p className="text-justify mb-4 space-y-4"><strong>8.4:</strong> Usted acepta que Nosotros, y los proveedores de servicios que utilizamos para ayudarle a proporcionarle el/los Servicio(s), tendremos derecho a acceder a Su Cuenta y a usar, modificar, reproducir, distribuir, mostrar y divulgar Sus Datos únicamente en la medida necesaria para proporcionar el/los Servicio(s), incluyendo, sin limitación, en respuesta a Sus solicitudes de soporte. Cualquier proveedor de servicios externo que utilicemos solo tendrá acceso a Su Cuenta y Sus Datos en la medida razonablemente necesaria para proporcionar el/los Servicio(s) y estará sujeto a obligaciones de confidencialidad. Skinner puede acceder o divulgar información sobre Usted, Su Cuenta, Usuarios, incluyendo Sus Datos, para (a) cumplir con la ley o responder a solicitudes o procesos legales; (b) proteger los derechos o la propiedad o de Nuestros clientes o socios, incluyendo la aplicación de estos Términos u otras políticas asociadas con el/los Servicio(s); (c) actuar de buena fe creyendo que dicha divulgación es necesaria para proteger la seguridad personal o evitar la violación de la ley o regulación aplicable. Además, a nuestra entera discreción, cualquier actividad sospechosa de ser fraudulenta, abusiva o ilegal por parte suya podrá ser remitida a las autoridades policiales.</p>
          <p className="text-justify mb-4 space-y-4"><strong>8.5:</strong> En la medida en que procesemos cualquier Dato Personal en su nombre en relación con el uso de los Servicios por parte de Usted y sus Usuarios, Usted y Nosotros acordamos que Usted será considerado el responsable del tratamiento de datos y Nosotros el encargado del tratamiento de datos.</p>
          <p className="text-justify mb-4 space-y-4">Al utilizar los Servicios, Usted consiente, en su nombre y en el de sus Usuarios (y declara tener la facultad de consentir en nombre de sus Usuarios), el Tratamiento de sus Datos, incluyendo, entre otros, cualquier Dato Personal, dentro de las Empresas del Grupo y a otros proveedores de servicios autorizados, de conformidad con estos Términos y nuestra Política de Privacidad.</p>
          <p className="text-justify mb-4 space-y-4"><strong>8.6 Recopilación de datos y privacidad:</strong> Recopilamos cierta información sobre usted, sus clientes y sus respectivos dispositivos, computadoras y el uso del/de los Servicio(s). Utilizamos, divulgamos y protegemos esta información como se describe en nuestra Política de Privacidad, que se incorpora a estos Términos por referencia.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl text-left font-semibold">9. COMUNICACIONES DE NUESTRA PARTE</h2>
          <p className="text-justify mb-4 space-y-4">Además de las comunicaciones especificadas en nuestra Política de Privacidad, podremos contactarle directamente por correo electrónico para notificarle si: Incumple estos Terminos.</p>
          <p className="text-justify mb-4 space-y-4">Se prohíbe una actividad o propósito específico con respecto al/los Servicio(s), por lo que deberá dejar de usar el/los Servicio(s) inmediatamente para dicha actividad o propósito prohibido ó Mantiene un número excepcionalmente alto de Usuarios o cualquier otra carga excesiva en el/los Servicio(s).</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl text-left font-semibold">10. EXENCIÓN DE GARANTÍAS</h2>
          <p className="text-justify mb-4 space-y-4"><strong>10.1:</strong> EL SITIO WEB Y EL/LOS SERVICIO(S), INCLUYENDO TODOS LOS COMPONENTES DE SERVIDOR Y RED, SE PROPORCIONAN &quot;TAL CUAL&quot; Y &quot;SEGÚN DISPONIBILIDAD&quot;, SIN GARANTÍAS DE NINGÚN TIPO, HASTA DONDE LO PERMITA LA LEY APLICABLE.</p>
          <p className="text-justify mb-4 space-y-4"><strong>10.2:</strong> USTED RECONOCE QUE NO GARANTIZAMOS QUE EL/LOS SERVICIO(S) O EL SITIO WEB SERÁN ININTERRUMPIDOS, OPORTUNOS, SEGUROS O LIBRES DE ERRORES. ADEMÁS, RECONOCE QUE NO GARANTIZAMOS QUE EL ACCESO AL/LOS SERVICIO(S), QUE SE PROPORCIONA A TRAVÉS DE INTERNET Y DIVERSAS REDES DE TELECOMUNICACIONES, TODAS LAS CUALES ESTÁN FUERA DE NUESTRO CONTROL, SERÁ ININTERRUMPIDO, OPORTUNO, SEGURO, LIBRE DE ERRORES O LIBRE DE VIRUS U OTRO SOFTWARE MALICIOSO.</p>
          </section>

        <section className="space-y-4">
          <h2 className="text-2xl text-left font-semibold">11. CESIÓN; ACUERDO COMPLETO; REVISIONES</h2> 
          <p className="text-justify mb-4 space-y-4"><strong>11.1:</strong> Usted no podrá, directa ni indirectamente, ceder la totalidad o parte de sus derechos bajo estos Términos ni delegar el cumplimiento de sus obligaciones bajo estos Términos sin nuestro consentimiento previo por escrito. Sujeto a las restricciones anteriores, estos Términos serán plenamente vinculantes para las partes y sus respectivos sucesores y cesionarios, redundarán en su beneficio y serán exigibles por ellas.</p>
          <p className="text-justify mb-4 space-y-4"><strong>11.2:</strong> Estos Términos, junto con cualquier Formulario, constituyen el acuerdo completo y sustituyen cualquier acuerdo previo entre Usted y Nosotros en relación con el objeto del presente. Estos Términos y cualquier Formulario prevalecerán sobre los términos o condiciones de cualquier orden de compra u otra documentación de pedido que Usted o cualquier Entidad que Usted represente proporcione (todos estos términos o condiciones serán nulos y sin valor) y, salvo que se indique expresamente en el presente, no existen otros acuerdos, declaraciones, garantías ni compromisos en los que ninguna de las partes pueda basarse con respecto al objeto del presente. En caso de conflicto entre cualquier Formulario y estos Términos, prevalecerán estos Términos.</p>
          <p className="text-justify mb-4 space-y-4"><strong>11.3:</strong> Sin perjuicio de lo anterior, podrían aplicarse términos adicionales a ciertas funciones o características que ofrecemos a través del/de los Servicio(s) (los &quot;Términos Adicionales&quot;). En tales casos, le notificaremos dichos Términos Adicionales antes de la activación de dichas funciones o características, y la activación de estas en su Cuenta se considerará como la aceptación de los Términos Adicionales. Todos estos Términos Adicionales se considerarán incorporados a estos Términos cuando usted o cualquier Usuario autorizado como administrador de su Cuenta active la función o característica. En caso de conflicto entre estos Términos y los Términos Adicionales, prevalecerán estos últimos respecto a dichas funciones o características.</p>
          <p className="text-justify mb-4 space-y-4"><strong>11.4:</strong> Podemos modificar estos Términos ocasionalmente, en cuyo caso los nuevos Términos sustituirán a las versiones anteriores. Lea atentamente estos Términos de uso antes de empezar a utilizar nuestros Servicios o Sitio Web, ya que se aplicarán a su uso de los Servicios y de nuestro Sitio Web. Consulte estos Términos periódicamente para estar al tanto de cualquier cambio que hayamos realizado, ya que serán vinculantes para usted. Le notificaremos con al menos diez (10) días de antelación a la fecha de entrada en vigor de dicha modificación, y su uso continuado de los Servicios tras la fecha de entrada en vigor de dicha modificación podrá considerarse como su consentimiento a la misma. El hecho de que no hagamos cumplir en cualquier momento alguna disposición de estos Términos no constituye una renuncia a dicha disposición ni a ninguna otra de los Términos.</p>
        </section>

         <section className="space-y-4">
          <h2 className="text-2xl text-left font-semibold">12. DIVISIBILIDAD; SIN RENUNCIA</h2>
          <p className="text-justify mb-4 space-y-4"><strong>12.1:</strong> Si cualquier disposición de estos Términos es considerada inaplicable por un tribunal de jurisdicción competente, referente al numeral 12.4 Podemos modificar estos Términos ocasionalmente, en cuyo caso los nuevos Términos sustituirán a las versiones anteriores. Lea atentamente estos Términos de uso antes de empezar a utilizar nuestros Servicios o Sitio Web, ya que se aplicarán a su uso de los Servicios y de nuestro Sitio Web. Consulte estos Términos periódicamente para estar al tanto de cualquier cambio que hayamos realizado, ya que serán vinculantes para usted. Le notificaremos con al menos diez (10) días de antelación a la fecha de entrada en vigor de dicha modificación, y su uso continuado de los Servicios tras la fecha de entrada en vigor de dicha modificación podrá considerarse como su consentimiento a la misma. El hecho de que no hagamos cumplir en cualquier momento alguna disposición de estos Términos no constituye una renuncia a dicha disposición ni a ninguna otra de los Términos. Nuestro no ejercicio de cualquier derecho o disposición de estos Términos no constituye una renuncia a ese derecho o disposición de los Términos.</p>
          <p className="text-justify mb-4 space-y-4"><strong>12.2 Enmienda; Sin Renuncia:</strong> Podemos actualizar y cambiar, total o parcialmente, nuestros Términos de Servicio, incluyendo las tarifas y cargos asociados al uso del Servicio de Suscripción (sin embargo, sus tarifas y cargos no cambiarán durante el Plazo de Suscripción, salvo como se explica en la sección &quot;Tarifas y Pagos&quot; anterior). Si actualizamos o cambiamos nuestros Términos de Servicio, los Términos de Servicio actualizados se publicarán en https://www.skinnersv.net/ y se lo notificaremos por correo electrónico o notificación en la aplicación. Los Términos de Servicio actualizados entrarán en vigor y serán vinculantes el siguiente día hábil a su publicación. Cuando modifiquemos nuestros Términos de Servicio, la fecha de &quot;Última Modificación&quot; anterior se actualizará para reflejar la fecha de la versión más reciente.</p>
          <p className="text-justify mb-4 space-y-4">Si no está de acuerdo con una modificación de nuestros Términos de Servicio, deberá notificarnos por escrito dentro de los treinta (30) días siguientes a la recepción de la notificación. Si nos notifica, su suscripción seguirá rigiéndose por los términos y condiciones de nuestros Términos de Servicio anteriores a la modificación durante el resto de su vigencia. Tras la renovación, se aplicarán los Términos de Servicio publicados en nuestro sitio web.</p>
          <p className="text-justify mb-4 space-y-4">La demora en el ejercicio de cualquier derecho o recurso, o la falta de objeción, no constituirá una renuncia a dicho derecho o recurso ni a ningún otro. Una renuncia en una ocasión no implicará una renuncia a ningún derecho o recurso en el futuro.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl text-left font-semibold">13. VIGENCIA</h2>
          <p className="text-justify mb-4 space-y-4">Las Secciones 2 (Sus Responsabilidades), 5 (Derechos de Propiedad Intelectual), 9 (Facturación, Modificación del Plan y Pagos), 7 (Suspensión y Terminación), 8 (Privacidad y Seguridad de los Datos; Confidencialidad), 10 (Exención de Garantías) seguirán vigentes tras la terminación de Nuestro acuerdo con respecto al uso del/de los Servicio(s) por su parte. La terminación de dicho acuerdo no limitará su responsabilidad ni la nuestra por las obligaciones contraídas a partir de dicha terminación o con anterioridad, ni por cualquier incumplimiento de estos Términos.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl text-left font-semibold">14. NOTIFICACIONES; CONSENTIMIENTO PARA COMUNICACIONES ELECTRÓNICAS</h2>
          <p className="text-justify mb-4 space-y-4"><strong>14.1:</strong> Todas las notificaciones que le enviemos en virtud de estos Términos podrán enviarse por correo electrónico a la dirección de correo electrónico proporcionada para su Cuenta.</p>
          <p className="text-justify mb-4 space-y-4"><strong>14.2:</strong> Nuestra dirección para notificaciones es info@skinnersv.net por correo electrónico. Todas las notificaciones se considerarán enviadas inmediatamente después de su entrega por correo electrónico.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl text-left font-semibold">15. LEY APLICABLE Y RESOLUCIÓN DE CONFLICTOS</h2>
          <p className="text-justify mb-4 space-y-4"><strong>15.1:</strong> Estos Términos se regirán por las leyes del gobierno de El Salvador, sin perjuicio de los principios de conflicto de leyes. Por la presente, usted acepta someterse expresamente a la jurisdicción personal exclusiva de los tribunales de El Salvador, para resolver cualquier disputa relacionada con los Términos o con su acceso o uso del/de los Servicio(s).</p>
        </section>


        <section className="space-y-4">
          <h2 className="text-2xl font-semibold">DESCARGO DE RESPONSABILIDAD</h2>
          <p className="text-justify mb-4 space-y-4">LOS MATERIALES CONTENIDOS EN EL SITIO Y LOS SERVICIOS DE SKINNER SE PROPORCIONAN &quot;TAL CUAL&quot;. SALVO LAS GARANTÍAS EXPRESAS CONTENIDAS EN ESTE ACUERDO, SKINNER NO OFRECE NINGUNA OTRA GARANTÍA, EXPRESA O IMPLÍCITA, Y POR LA PRESENTE RENUNCIA Y NIEGA TODAS LAS DEMÁS GARANTÍAS, INCLUYENDO, ENTRE OTRAS, LAS GARANTÍAS O CONDICIONES IMPLÍCITAS DE COMERCIABILIDAD, IDONEIDAD PARA UN FIN DETERMINADO U OTRAS VIOLACIONES DE DERECHOS. ADEMÁS, SKINNER NO GARANTIZA NI HACE DECLARACIÓN ALGUNA SOBRE LA EXACTITUD, LOS RESULTADOS PROBABLES O LA FIABILIDAD DEL USO DE LOS MATERIALES EN SU SITIO O SERVICIOS, NI EN RELACIÓN CON DICHOS MATERIALES O EN SITIOS O SERVICIOS DE TERCEROS ENLAZADOS DENTRO DEL SITIO O SERVICIOS, NI SOBRE QUE LOS SERVICIOS ESTARÁN LIBRES DE ERRORES O PROPORCIONARÁN CIERTOS RESULTADOS.</p>
          <p className="text-justify mb-4 space-y-4">USTED RECONOCE HABER LEÍDO ESTE ACUERDO, LO HA ENTENDIDO Y ACEPTA SUS TÉRMINOS.</p>
          <p className="text-justify mb-4 space-y-4">INFORMACIÓN DE CONTACTO</p>
          <p className="text-justify mb-4 space-y-4">Skinner, S.A.S de C.V.</p>
          <p className="text-justify mb-4 space-y-4">Santa tecla, La Libertad Sur</p>
          <p className="text-justify mb-4 space-y-4">El Salvador, Centro América</p>
          <p className="text-justify mb-4 space-y-4">info@skinnersv.net</p>
          <p className="text-justify mb-4 space-y-4">21 de mayo de 2025</p>

        </section>
        
        <div className="flex justify-center pt-4">
          <Link
            href="/"
            className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus-visible:outline-hidden focus-visible:ring-1 focus-visible:ring-ring"
          >
            Regresa a Casa
          </Link>
        </div>
      </div>
    </div>
  )
}
